export const MOCK_PRODUCTS = [
  {
    _id: 'mock-1',
    name: 'MKX Core Platform',
    description: 'The foundation of your digital transformation.',
    icon: 'layout',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: 'mock-2',
    name: 'MKX Analytics Engine',
    description: 'Advanced insights powered by AI.',
    icon: 'bar-chart',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: 'mock-3',
    name: 'MKX Enterprise Security',
    description: 'Protecting your data with state-of-the-art encryption.',
    icon: 'shield',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  }
]

export const MOCK_PRICING_PLANS = [
  {
    _id: 'plan-1',
    name: 'Starter',
    price: 49,
    interval: 'MONTH',
    features: ['Up to 5 users', 'Basic analytics', 'Email support'],
    isPopular: false,
    isActive: true,
    productId: 'mock-1',
    productName: 'MKX Core Platform',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: 'plan-2',
    name: 'Pro',
    price: 99,
    interval: 'MONTH',
    features: ['Up to 20 users', 'Advanced analytics', 'Priority support', 'API access'],
    isPopular: true,
    isActive: true,
    productId: 'mock-1',
    productName: 'MKX Core Platform',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: 'plan-3',
    name: 'Enterprise',
    price: 299,
    interval: 'MONTH',
    features: ['Unlimited users', 'Custom integration', 'Dedicated account manager', '24/7 phone support'],
    isPopular: false,
    isActive: true,
    productId: 'mock-1',
    productName: 'MKX Core Platform',
    createdAt: new Date(),
    updatedAt: new Date(),
  }
]
